version: 2.1
setup: true

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

defaults: &defaults
  working_directory: ~/samvaad
  docker:
    - image: cimg/python:3.9
  resource_class: small
orbs:
  continuation: circleci/continuation@0.4.0

jobs:
  CalculateChanges:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install python deps
          command: |
            python3.9 -m pip install import_deps==0.2.0 PyYAML requests

      - run:
          name: Identify Changes
          command: |
              python3.9 calculate_changes.py --branch develop  # for testing only

      - continuation/continue:
          configuration_path: .circleci/workflow.yml

workflows:
  version:
  checking-file-changes:
    jobs:
      - CalculateChanges:
          context: global-vars
