version: 2.1

parameters:
  my_trigger_parameter:
    type: string
    default: ""

workflows:
  # Workflow triggered by API call / hitting "Trigger Pipeline" in the web interface
  api-triggered-workflow:
    when: << pipeline.parameters.my_trigger_parameter >>
    jobs:
    - Test-Hold:
        name: Test-Hold
        type: approval
        matrix:
          parameters:
            requirements_file: [ ]
    - do-the-thing1:
        my_job_param: << pipeline.parameters.my_trigger_parameter >>
        requires:
        - Test-Hold
  # Workflow triggered only by pushing a commit to the repository
  commit-triggered-workflow:
    when:
      not: << pipeline.parameters.my_trigger_parameter >>
    jobs:
    - do-the-thing

jobs:
  do-the-thing:
    docker:
      - image: cimg/python:3.11
    parameters:
      my_job_param:
        type: string
        default: "triggered by commit"
    steps:
      - checkout
      - run: python testing.py
      - run: python testing1.py
  do-the-thing1:
    docker:
      - image: cimg/base:2020.01
    parameters:
      my_job_param:
        type: string
        default: "triggered by commit"
    steps:
      - run: echo "running rollback"
      - run: python testing.py
      # - run: 
      #   name: run rollback job
      #   command: |
      #     curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
      #     --header 'Content-Type: application/json' \
      #     -u "${CIRCLE_TOKEN}:" \
      #     -d '{
      #                   "parameters": {
      #                     "rollback_job": true
      #                   }
      #                 }'